production:
  solr:
    hostname: localhost
    port: 8984 #8983
    log_level: WARNING
    path: /solr/production
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    hostname: localhost
    port: 8985 #8982
    log_level: INFO
    path: /solr/development

test:
  solr:
    hostname: localhost
    port: 8986 #8981
    log_level: WARNING
    path: /solr/test
    
